### ISSUE TITLE
GitHub copilot coding agent cannot run code on the repository

### ISSUE THREAD

**Issue by tbennun** [spcl/dace#2023]
It looks like GitHub Copilot needs some initial setup file in order to install dependencies and run Python code that uses DaCe: https://docs.github.com/en/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent

To summarize:
If GitHub Copilot is unable to install dependencies in its ephemeral development environment, you can preconfigure Copilot's environment by creating a special GitHub Actions workflow file named `.github/workflows/copilot-setup-steps.yml` in your repository.

Here’s how you can set it up:

1.  **Create the Workflow File**:
    
    *   In your repository, create a file at `.github/workflows/copilot-setup-steps.yml`.
2.  **Define the Setup Steps**:
    
    *   Add the following example configuration to the file, customizing it for your project's language and dependencies. For example:

```
    name: "Copilot Setup Steps"
    on: workflow_dispatch
    jobs:
      copilot-setup-steps:
        runs-on: ubuntu-latest
        permissions:
          contents: read
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: "20"
              cache: "npm"
          - name: Install JavaScript dependencies
            run: npm ci
```    

3.  **Customize Settings**:
    
    *   Ensure the job is named `copilot-setup-steps` as Copilot will only recognize this specific job name.
    *   You can customize the `steps`, `permissions`, `runs-on`, `container`, `services`, `snapshot`, and `timeout-minutes` (maximum value: 59) settings.

You would need to adapt it for the Python/PyPI dependencies necessary to run DaCe
